name = input("Please enter your name: ")
print("Hi {name} >> Welcome to GitHub <<")
print("This is the second version")
print("This is the third version")
print("This is the code for 4th version in the cloudC branch")